name: Build Android APK
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Find and Unzip Code
        run: |
          unzip -o *.zip || true
          # Agar zip ke andar ek aur folder hai toh uski files ko bahar nikalne ke liye
          cp -r sarvagya-study-hub*/* . || true
          cp -r studyhub*/* . || true
          ls -la
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SarvagyaStudyHub-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          
